export type Word = {
  word: string;
  category: string;
};

export const wordsArray: Word[] = [
  { word: "ocean", category: "Nature" },
  { word: "puzzle", category: "Objects" },
  { word: "guitar", category: "Music" },
  { word: "jungle", category: "Nature" },
  { word: "castle", category: "Architecture" },
  { word: "wizard", category: "Fantasy" },
  { word: "ballet", category: "Dance" },
  { word: "laptop", category: "Technology" },
  { word: "volcano", category: "Nature" },
  { word: "glacier", category: "Nature" },
  { word: "kitten", category: "Animals" },
  { word: "museum", category: "Places" },
  { word: "recipe", category: "Food" },
  { word: "comedy", category: "Entertainment" },
  { word: "pirate", category: "Fantasy" },
  { word: "sphinx", category: "Mythology" },
  { word: "jacket", category: "Clothing" },
  { word: "gadget", category: "Technology" },
  { word: "fossil", category: "Science" },
  { word: "harvest", category: "Agriculture" },
  { word: "metropolitan", category: "Places" },
  { word: "archaeology", category: "Science" },
  { word: "conundrum", category: "Concepts" },
  { word: "philosophy", category: "Academics" },
  { word: "biotechnology", category: "Science" },
  { word: "antioxidant", category: "Health" },
  { word: "cartography", category: "Art" },
  { word: "microscope", category: "Science" },
  { word: "revolutionary", category: "History" },
  { word: "sustainability", category: "Environment" },
];

// Version with actual hints instead of category
// export const wordsArray: Word[] = [
//   { word: "ocean", wordHint: "Vast blue expanse" },
//   { word: "puzzle", wordHint: "Brain teaser" },
//   { word: "guitar", wordHint: "String musical instrument" },
//   { word: "jungle", wordHint: "Dense tropical forest" },
//   { word: "castle", wordHint: "Medieval fortress" },
//   { word: "wizard", wordHint: "Magic practitioner" },
//   { word: "ballet", wordHint: "Classical dance form" },
//   { word: "laptop", wordHint: "Portable computer" },
//   { word: "volcano", wordHint: "Erupting mountain" },
//   { word: "glacier", wordHint: "Slow-moving ice" },
//   { word: "kitten", wordHint: "Young domestic cat" },
//   { word: "museum", wordHint: "Artifacts display place" },
//   { word: "recipe", wordHint: "Cooking instructions" },
//   { word: "comedy", wordHint: "Humorous entertainment" },
//   { word: "pirate", wordHint: "Sea robber" },
//   { word: "sphinx", wordHint: "Egyptian mythical creature" },
//   { word: "jacket", wordHint: "Outerwear garment" },
//   { word: "gadget", wordHint: "Small device or tool" },
//   { word: "fossil", wordHint: "Preserved ancient remains" },
//   { word: "harvest", wordHint: "Crop gathering" },
//   { word: "metropolitan", wordHint: "Large urban city" },
//   { word: "archaeology", wordHint: "Ancient artifact study" },
//   { word: "conundrum", wordHint: "Difficult problem" },
//   { word: "philosophy", wordHint: "Study of existence" },
//   { word: "biotechnology", wordHint: "Biology-based technology" },
//   { word: "antioxidant", wordHint: "Prevents oxidation" },
//   { word: "cartography", wordHint: "Map making art" },
//   { word: "microscope", wordHint: "Magnifies small objects" },
//   { word: "revolutionary", wordHint: "Radical change agent" },
//   { word: "sustainability", wordHint: "Eco-friendly practice" },
// ];